pub use crate::manager::{
    ActivityType, DeviceOrientation, LocationManager, LocationManagerCallbacks,
    LocationManagerDelegate, LocationManagerErrorInfo, DISTANCE_FILTER_NONE, HEADING_FILTER_NONE,
    LOCATION_ACCURACY_BEST, LOCATION_ACCURACY_BEST_FOR_NAVIGATION,
    LOCATION_ACCURACY_HUNDRED_METERS, LOCATION_ACCURACY_KILOMETER,
    LOCATION_ACCURACY_NEAREST_TEN_METERS, LOCATION_ACCURACY_THREE_KILOMETERS,
};
